"""Criação inicial do banco

Revision ID: a96d6c672c3d
Revises: 
Create Date: 2025-03-19 21:10:49.470175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96d6c672c3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('venda_produto', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('venda_produto', sa.Column('id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('venda_produto', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_venda_produto_id'), 'venda_produto', ['id'], unique=False)
    op.create_foreign_key(None, 'venda_produto', 'vendas', ['venda_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venda_produto', type_='foreignkey')
    op.drop_index(op.f('ix_venda_produto_id'), table_name='venda_produto')
    op.alter_column('venda_produto', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('venda_produto', 'id')
    # ### end Alembic commands ###
